### ISSUE TITLE
서비스 부분에서 비밀번호

### ISSUE THREAD

**Issue by gilgyujeong** [gilgyujeong/board#1]
id값이 있는지 확인 하고 비밀번호 확인 하는데 만약 id가 없으면 확인할 필요가 없으니 지금 로직 처럼 하면 되는가 만약 없으면 null 값이 들어가서 오류가 발생하게 되는데 어떻게 해야될요?

**Comment by slsnrnsep** [comment]
안녕하세요 길규님! 질문 주신 내용에 답하게 된 정영호라고 합니다. 

우선 게시글의 수정,삭제등을 할때 ID값을 client에게 받아서 해당하는 ID의 게시글이 있는지 확인 후(findBoard)
있으면 update하도록 하는 현재 로직을 유지해주시면 되겠습니다.

id값이 DB에 없어서 에러가발생하는 경우는 정상 비즈니스 로직이므로 잘못된 ID값을 입력했다던가, 데이터를 찾을 수 없습니다.와 같은 에러메시지를 response로 주시면 되겠습니다.

그 외 전체적인 level1 과제 요구사항에 맞게 잘 수행해주셨으나 application.properties 의 DB정보(비밀번호,url) 올라와있어서, 로컬디비라 안전하긴 하지만 다음부터의 github에 올릴때에는 민감정보들을 제외하고 올려주시면 더욱 좋을 것 같습니다!
추가로 jsonIgnore로 password필드부분을 변환하지 않도록 하기 보다는, reponsedto를 현재 잘 사용하고 계시므로 해당 어노테이션 제거해도 괜찮아보입니다. 과제하시느라 고생하셨으며 앞으로도 쭉쭉 화이팅입니다!
