### ISSUE TITLE
코드 리뷰입니다

### ISSUE THREAD

**Issue by Goonerd17** [gilgyujeong/board#2]
조회를 제외하고 RequestBody를 사용하셨고 각 기능에 맞게 HTTP메서드는 잘 사용한 거 같습니다 관심사가 Controller, Repository, Service에 맞게 분리되어 있고 해당 3계층이 모두 각자의 역할이 명확하게 구분되어 있는 모습도 볼 수 있었습니다. 코드가 간결하고 읽기 쉬운 거 같네요 주어진 API 명세를 대부분 적용하신 점도 훌륭했습니다. 다만 컨트롤러의 삭제 부분의 리턴값이 id인데, 이를 API 명세에 맞게 success:true로 바꿔주시면 좋을 것 같아요. 추가적으로 서비스에서 발생할 수 있는 예외들을 HTTP 상태코드에 맞게 설정해주시면 더 좋을 것 같습니다. 1주차 과제하시느라 수고하셨습니다!

**Comment by gilgyujeong** [comment]
반환 형태까지 생각해보지 못했네요 데이터베이스 결과만 신경쓰다 보니 생각을 하지 못한 것 같습니다. 예외 처리를 아직 잘몰라서 학습하고 수정해보겠습니다. ^^ 감사합니다.
